INFO 2022-05-25 11:29:56,795 autoreload 19224 27216 Watching for file changes with StatReloader
INFO 2022-05-25 12:41:30,401 autoreload 4624 60556 Watching for file changes with StatReloader
INFO 2022-05-25 12:43:46,618 autoreload 57724 34664 Watching for file changes with StatReloader
INFO 2022-05-25 12:44:02,007 autoreload 43380 20980 Watching for file changes with StatReloader
INFO 2022-05-25 12:49:19,621 autoreload 10872 42828 Watching for file changes with StatReloader
INFO 2022-05-25 12:49:59,357 autoreload 60888 27192 Watching for file changes with StatReloader
INFO 2022-05-25 13:12:02,612 autoreload 1468 24828 Watching for file changes with StatReloader
WARNING 2022-05-25 13:12:06,632 log 1468 11616 Not Found: /
WARNING 2022-05-25 13:12:06,688 log 1468 11616 Not Found: /favicon.ico
INFO 2022-05-25 13:13:52,363 autoreload 21852 6408 Watching for file changes with StatReloader
WARNING 2022-05-25 13:14:04,043 log 21852 21540 Not Found: /favicon.ico
ERROR 2022-05-25 13:14:38,098 log 21852 21540 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 173, in register
    form.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\forms.py", line 143, in save
    user.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id
INFO 2022-05-25 13:25:51,792 autoreload 21852 6408 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\forms.py changed, reloading.
INFO 2022-05-25 13:25:52,101 autoreload 20836 24616 Watching for file changes with StatReloader
WARNING 2022-05-25 13:26:03,347 log 20836 23924 Not Found: /
ERROR 2022-05-25 13:26:31,503 log 20836 23924 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 172, in register
    if form.is_valid():
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\forms\forms.py", line 205, in is_valid
    return self.is_bound and not self.errors
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\forms\forms.py", line 200, in errors
    self.full_clean()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\forms\forms.py", line 435, in full_clean
    self._post_clean()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\forms.py", line 129, in _post_clean
    super()._post_clean()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\forms\models.py", line 485, in _post_clean
    self.instance = construct_instance(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\forms\models.py", line 82, in construct_instance
    f.save_form_data(instance, cleaned_data[f.name])
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\fields\__init__.py", line 991, in save_form_data
    setattr(instance, self.name, data)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "1": "Account.account_role" must be a "Account_Role" instance.
INFO 2022-05-25 13:27:52,280 autoreload 20836 24616 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\forms.py changed, reloading.
INFO 2022-05-25 13:27:52,596 autoreload 8944 6432 Watching for file changes with StatReloader
INFO 2022-05-25 13:32:45,956 autoreload 8944 6432 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 13:32:46,278 autoreload 8180 23952 Watching for file changes with StatReloader
ERROR 2022-05-25 13:32:51,442 log 8180 22716 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 174, in register
    form.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\forms.py", line 143, in save
    user.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id
INFO 2022-05-25 13:34:04,439 autoreload 8180 23952 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 13:34:04,753 autoreload 10528 17324 Watching for file changes with StatReloader
ERROR 2022-05-25 13:34:08,156 log 10528 20284 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 174, in register
    form.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\forms.py", line 143, in save
    user.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id
ERROR 2022-05-25 13:34:21,294 log 10528 20284 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 174, in register
    form.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\forms.py", line 143, in save
    user.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id
INFO 2022-05-25 13:45:53,075 autoreload 19900 13524 Watching for file changes with StatReloader
INFO 2022-05-25 13:46:00,401 autoreload 19900 13524 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 13:46:00,712 autoreload 4176 20968 Watching for file changes with StatReloader
INFO 2022-05-25 13:46:36,631 autoreload 4176 20968 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 13:46:36,940 autoreload 9636 9088 Watching for file changes with StatReloader
ERROR 2022-05-25 13:46:43,109 log 9636 1860 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 173, in register
    form.account_role = models.Account_Role.objects.get(pk = 1)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
flight_app.models.Account_Role.DoesNotExist: Account_Role matching query does not exist.
INFO 2022-05-25 13:48:37,801 autoreload 11596 22092 Watching for file changes with StatReloader
ERROR 2022-05-25 13:48:46,388 log 11596 1512 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 173, in register
    form.account_role = models.Account_Role.objects.get(pk = 1)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
flight_app.models.Account_Role.DoesNotExist: Account_Role matching query does not exist.
INFO 2022-05-25 13:49:47,984 autoreload 16276 19336 Watching for file changes with StatReloader
ERROR 2022-05-25 13:50:04,829 log 16276 9096 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 173, in register
    form.account_role = models.Account_Role.objects.get(pk = 1)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
flight_app.models.Account_Role.DoesNotExist: Account_Role matching query does not exist.
INFO 2022-05-25 13:50:28,221 autoreload 16276 19336 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 13:50:28,524 autoreload 24980 8652 Watching for file changes with StatReloader
ERROR 2022-05-25 13:50:41,775 log 24980 24244 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 173, in register
    form.account_role = models.Account_Role.objects.get(pk = 1)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
flight_app.models.Account_Role.DoesNotExist: Account_Role matching query does not exist.
INFO 2022-05-25 14:16:23,049 autoreload 7720 14772 Watching for file changes with StatReloader
ERROR 2022-05-25 14:17:31,762 log 7720 15736 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 173, in register
    form.account_role = models.Account_Role.objects.get(pk = 1)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
flight_app.models.Account_Role.DoesNotExist: Account_Role matching query does not exist.
INFO 2022-05-25 14:22:14,063 autoreload 15164 10480 Watching for file changes with StatReloader
ERROR 2022-05-25 14:22:19,081 log 15164 1004 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 173, in register
    form.account_role = models.Account_Role.objects.get(id = 1)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
flight_app.models.Account_Role.DoesNotExist: Account_Role matching query does not exist.
INFO 2022-05-25 14:24:05,903 autoreload 15164 10480 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 14:24:06,217 autoreload 22912 12356 Watching for file changes with StatReloader
ERROR 2022-05-25 14:24:40,877 log 22912 16568 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 174, in register
    form.account_role = models.Account_Role.objects.get(id = accuunt_role)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
flight_app.models.Account_Role.DoesNotExist: Account_Role matching query does not exist.
INFO 2022-05-25 14:25:16,176 autoreload 22912 12356 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\models.py changed, reloading.
INFO 2022-05-25 14:25:16,528 autoreload 11508 3984 Watching for file changes with StatReloader
INFO 2022-05-25 14:27:04,191 autoreload 11508 3984 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\models.py changed, reloading.
INFO 2022-05-25 14:27:04,530 autoreload 19592 11272 Watching for file changes with StatReloader
INFO 2022-05-25 14:29:39,412 autoreload 19592 11272 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 14:29:39,721 autoreload 6172 18036 Watching for file changes with StatReloader
ERROR 2022-05-25 14:29:45,576 log 6172 17136 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 175, in register
    form.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\forms.py", line 143, in save
    user.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id
INFO 2022-05-25 14:43:58,463 autoreload 6172 18036 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 14:43:58,777 autoreload 4828 10280 Watching for file changes with StatReloader
INFO 2022-05-25 14:43:59,988 autoreload 4828 10280 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\DAL\base_facade.py changed, reloading.
INFO 2022-05-25 14:44:00,304 autoreload 5304 8716 Watching for file changes with StatReloader
INFO 2022-05-25 14:45:25,538 autoreload 5304 8716 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 14:45:25,858 autoreload 12064 17752 Watching for file changes with StatReloader
ERROR 2022-05-25 14:45:37,231 log 12064 4004 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\forms\forms.py", line 182, in __getitem__
    field = self.fields[name]
KeyError: 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 178, in register
    new_user.password = form['password']
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\forms\forms.py", line 184, in __getitem__
    raise KeyError(
KeyError: "Key 'password' not found in 'RegistrationForm'. Choices are: email, password1, password2, username."
INFO 2022-05-25 14:46:38,825 autoreload 12064 17752 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 14:46:39,127 autoreload 17656 22420 Watching for file changes with StatReloader
ERROR 2022-05-25 14:46:42,913 log 17656 6784 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 187, in register
    login(request,account)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\__init__.py", line 138, in login
    request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\utils\functional.py", line 259, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute '_meta'
INFO 2022-05-25 14:50:03,053 autoreload 17656 22420 D:\Full_Stack\Projects\Second_Project\Flight_System\Flight_System\settings\dev_set.py changed, reloading.
INFO 2022-05-25 14:50:03,361 autoreload 19112 17680 Watching for file changes with StatReloader
ERROR 2022-05-25 14:50:40,574 log 19112 20464 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 187, in register
    login(request,account)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\__init__.py", line 138, in login
    request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\utils\functional.py", line 259, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute '_meta'
INFO 2022-05-25 14:57:42,421 autoreload 19112 17680 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 14:57:42,735 autoreload 15236 12208 Watching for file changes with StatReloader
ERROR 2022-05-25 14:58:19,403 log 15236 20008 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 179, in register
    form.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\forms.py", line 143, in save
    user.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id
INFO 2022-05-25 15:01:52,803 autoreload 15236 12208 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 15:01:53,120 autoreload 18064 24328 Watching for file changes with StatReloader
ERROR 2022-05-25 15:01:56,597 log 18064 17444 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 179, in register
    form.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\forms.py", line 143, in save
    user.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id
ERROR 2022-05-25 15:02:27,112 log 18064 17444 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 179, in register
    form.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\forms.py", line 143, in save
    user.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id
INFO 2022-05-25 15:04:02,370 autoreload 18064 24328 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 15:04:02,679 autoreload 6860 13928 Watching for file changes with StatReloader
ERROR 2022-05-25 15:04:08,546 log 6860 20500 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 178, in register
    new_user.account_role =  models.Account_Role.objects.get(pk = user_role)
AttributeError: 'method' object has no attribute 'account_role'
INFO 2022-05-25 15:04:27,528 autoreload 6860 13928 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 15:04:27,841 autoreload 2616 1088 Watching for file changes with StatReloader
ERROR 2022-05-25 15:04:31,587 log 2616 9424 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 175, in register
    new_user = form.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\forms.py", line 143, in save
    user.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id
INFO 2022-05-25 15:04:45,460 autoreload 2616 1088 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 15:04:45,779 autoreload 24088 18220 Watching for file changes with StatReloader
ERROR 2022-05-25 15:04:59,176 log 24088 20572 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 180, in register
    new_user.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\forms.py", line 143, in save
    user.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id
INFO 2022-05-25 15:05:29,997 autoreload 24088 18220 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 15:05:30,311 autoreload 21176 8748 Watching for file changes with StatReloader
ERROR 2022-05-25 15:05:34,375 log 21176 12120 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 176, in register
    raise Exception ({new_user})
Exception: {<RegistrationForm bound=True, valid=True, fields=(email;username;password1;password2)>}
INFO 2022-05-25 15:11:00,225 autoreload 21176 8748 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\forms.py changed, reloading.
INFO 2022-05-25 15:11:00,543 autoreload 8676 4656 Watching for file changes with StatReloader
INFO 2022-05-25 15:11:31,509 autoreload 8676 4656 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\forms.py changed, reloading.
INFO 2022-05-25 15:11:31,822 autoreload 18368 23900 Watching for file changes with StatReloader
INFO 2022-05-25 15:11:33,009 autoreload 18368 23900 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 15:11:33,327 autoreload 19004 16268 Watching for file changes with StatReloader
WARNING 2022-05-25 15:11:36,571 log 19004 16880 Not Found: /flight_app/login/
INFO 2022-05-25 15:12:00,243 autoreload 19004 16268 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\forms.py changed, reloading.
INFO 2022-05-25 15:12:00,550 autoreload 19140 20908 Watching for file changes with StatReloader
INFO 2022-05-25 15:12:07,867 autoreload 19140 20908 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\forms.py changed, reloading.
INFO 2022-05-25 15:12:08,167 autoreload 21656 6780 Watching for file changes with StatReloader
INFO 2022-05-25 15:14:08,129 autoreload 21656 6780 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\forms.py changed, reloading.
INFO 2022-05-25 15:14:08,430 autoreload 10536 15236 Watching for file changes with StatReloader
WARNING 2022-05-25 15:14:22,292 log 10536 10168 Not Found: /flight_app/register/login
WARNING 2022-05-25 15:14:27,316 log 10536 8048 Not Found: /flight_app/register/register
INFO 2022-05-25 15:16:20,798 autoreload 10536 15236 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 15:16:21,107 autoreload 1844 4068 Watching for file changes with StatReloader
ERROR 2022-05-25 15:16:42,548 log 1844 11988 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 173, in register
    form.add
AttributeError: 'RegistrationForm' object has no attribute 'add'
INFO 2022-05-25 15:18:31,419 autoreload 1844 4068 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 15:18:31,746 autoreload 10600 10088 Watching for file changes with StatReloader
ERROR 2022-05-25 15:18:35,598 log 10600 5148 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 175, in register
    form.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\forms.py", line 143, in save
    user.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id
INFO 2022-05-25 15:18:48,350 autoreload 10600 10088 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 15:18:48,646 autoreload 17712 19072 Watching for file changes with StatReloader
INFO 2022-05-25 15:18:50,849 autoreload 17712 19072 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\forms.py changed, reloading.
INFO 2022-05-25 15:18:51,149 autoreload 18404 11400 Watching for file changes with StatReloader
ERROR 2022-05-25 15:18:54,122 log 18404 14284 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 175, in register
    form.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\forms.py", line 143, in save
    user.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id
INFO 2022-05-25 15:19:14,912 autoreload 18404 11400 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py changed, reloading.
INFO 2022-05-25 15:19:15,210 autoreload 15476 13892 Watching for file changes with StatReloader
ERROR 2022-05-25 15:19:24,453 log 15476 23032 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 174, in register
    form.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\forms.py", line 143, in save
    user.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id
INFO 2022-05-25 15:20:28,218 autoreload 15476 13892 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\forms.py changed, reloading.
INFO 2022-05-25 15:20:28,534 autoreload 1852 2364 Watching for file changes with StatReloader
INFO 2022-05-25 15:20:38,986 autoreload 1852 2364 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\forms.py changed, reloading.
INFO 2022-05-25 15:20:39,275 autoreload 23900 5816 Watching for file changes with StatReloader
INFO 2022-05-25 15:20:45,618 autoreload 23900 5816 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\forms.py changed, reloading.
INFO 2022-05-25 15:20:45,933 autoreload 3784 21288 Watching for file changes with StatReloader
INFO 2022-05-25 15:21:00,519 autoreload 3784 21288 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\forms.py changed, reloading.
INFO 2022-05-25 15:21:00,824 autoreload 21068 14788 Watching for file changes with StatReloader
ERROR 2022-05-25 15:21:03,488 log 21068 14104 Internal Server Error: /flight_app/register/
Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\views.py", line 174, in register
    form.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\forms.py", line 143, in save
    user.save()
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\contrib\auth\base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Full_Stack\Projects\Second_Project\Flight_System\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: flight_app_account.account_role_id
INFO 2022-05-25 15:21:18,503 autoreload 21068 14788 D:\Full_Stack\Projects\Second_Project\Flight_System\flight_app\forms.py changed, reloading.
INFO 2022-05-25 15:21:18,827 autoreload 18616 22504 Watching for file changes with StatReloader
